server:
  port: 8080

spring:
  application:
    name: service1

service-two:
  uri: ${SERVICE_2_URI:http://localhost:8081/api/v1/service2}

service-three:
  uri: ${SERVICE_3_URI:http://localhost:8082/api/v1/service3}

zipkin:
  base-url: ${ZIPKIN_URl:http://locahost:9411}