server:
  port: ${SERVICE_1_PORT:8080}

spring:
  application:
    name: service1
  zipkin:
    base-url: ${ZIPKIN_URl:http://localhost:9411}

service-two:
  uri: ${SERVICE_2_URI:http://localhost:8081/api/v1/service2}

service-three:
  uri: ${SERVICE_3_URI:http://localhost:8082/api/v1/service3}

